### ISSUE TITLE
Attempt to subtract with overflow in `get_docids_for_value_range`

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/tantivy#1779]
**Describe the bug**
Observed in Quickwit

Search query:
```
service_name:quickwit AND span_start_timestamp_nanos:[2023-01-11T17:50:07Z TO 2023-01-11T18:50:07Z]
```

Aggregation query:
```json
"trace_ids": {
    "terms": {
        "field": "trace_id",
        "size": 20,
        "order": {
            "span_start_timestamp_nanos_stats.max": "desc"
        }
    },
    "aggs": {
        "span_start_timestamp_nanos_stats": {
            "stats": {
                "field": "span_start_timestamp_nanos"
            }
        }
    }
}
```

Doc mapping:
```yaml
field_mappings:
  - name: trace_id
    type: text
    tokenizer: raw
    fast: true
  - name: trace_state
    type: text
    indexed: false
  - name: resource_attributes
    type: json
    tokenizer: raw
  - name: resource_dropped_attributes_count
    type: u64
    indexed: false
  - name: service_name
    type: text
    tokenizer: raw
  - name: span_id
    type: text
    tokenizer: raw
  - name: span_kind
    type: u64
  - name: span_name
    type: text
    tokenizer: raw
  - name: span_start_timestamp_nanos
    type: datetime
    input_formats:
      - unix_timestamp
    indexed: false
    fast: true
    precision: seconds
  - name: span_end_timestamp_nanos
    type: u64
    indexed: false
  - name: span_duration_millis
    type: u64
    stored: false
    indexed: false
    fast: true
  - name: span_attributes
    type: json
    tokenizer: raw
  - name: span_dropped_attributes_count
    type: u64
    indexed: false
  - name: span_dropped_events_count
    type: u64
    indexed: false
  - name: span_dropped_links_count
    type: u64
    indexed: false
  - name: span_status
    type: json
    indexed: false
  - name: parent_span_id
    type: text
    indexed: false
  - name: events
    type: array<json>
    tokenizer: raw
  - name: links
    type: array<json>
    tokenizer: raw
```

Stacktrace
```
2023-01-11T18:50:07.273Z  INFO leaf_search: quickwit_search::service: leaf_search index="otel-trace-v0" splits=[SplitIdAndFooterOffsets { split_id: "01GPH2B1HW47X7CY2PWEQR4CJ7", split_footer_start: 9709, split_footer_end: 18717 }]
thread 'quickwit-search-0' panicked at 'attempt to subtract with overflow', /Users/guilload/.cargo/git/checkouts/tantivy-f70b7ea03dadae9a/f8d111a/fastfield_codecs/src/monotonic_mapping.rs:138:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
   3: <fastfield_codecs::column::MonotonicMappingColumn<C,T,Input> as fastfield_codecs::column::Column<Output>>::get_docids_for_value_range
   4: tantivy::query::range_query::fast_field_range_query::RangeDocSet<T>::fetch_horizon
   5: tantivy::query::range_query::fast_field_range_query::RangeDocSet<T>::fetch_block
   6: tantivy::query::range_query::fast_field_range_query::RangeDocSet<T>::new
   7: <tantivy::query::range_query::range_query_u64_fastfield::FastFieldRangeWeight as tantivy::query::weight::Weight>::scorer
   8: tantivy::query::boolean_query::boolean_weight::BooleanWeight<TScoreCombiner>::per_occur_scorers
   9: tantivy::query::boolean_query::boolean_weight::BooleanWeight<TScoreCombiner>::complex_scorer
  10: <tantivy::query::boolean_query::boolean_weight::BooleanWeight<TScoreCombiner> as tantivy::query::weight::Weight>::for_each_no_score
  11: tantivy::collector::Collector::collect_segment
  12: tantivy::core::searcher::Searcher::search_with_executor::{{closure}}
  13: core::iter::adapters::map::map_try_fold::{{closure}}
  14: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold::enumerate::{{closure}}
  15: core::iter::traits::iterator::Iterator::try_fold
  16: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::try_fold
  17: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  18: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
  19: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
  21: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  22: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
  23: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
  24: core::iter::adapters::try_process
  25: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
  26: core::iter::traits::iterator::Iterator::collect
  27: tantivy::core::executor::Executor::map
  28: tantivy::core::searcher::Searcher::search_with_executor
  29: tantivy::core::searcher::Searcher::search
  30: quickwit_search::leaf::leaf_search_single_split::{{closure}}::{{closure}}::{{closure}}
  31: quickwit_search::thread_pool::run_cpu_intensive::{{closure}}::{{closure}}
  32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  33: std::panicking::try::do_call
  34: ___rust_try
  35: std::panicking::try
  36: std::panic::catch_unwind
  37: rayon_core::unwind::halt_unwinding
  38: rayon_core::registry::Registry::catch_unwind
  39: rayon_core::spawn::spawn_job::{{closure}}
  40: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
  41: rayon_core::job::JobRef::execute
  42: rayon_core::registry::WorkerThread::execute
  43: rayon_core::registry::WorkerThread::wait_until_cold
  44: rayon_core::registry::WorkerThread::wait_until
  45: rayon_core::registry::main_loop
  46: rayon_core::registry::ThreadBuilder::run
  47: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
```

**Which version of tantivy are you using?**
`main`

**To Reproduce**
In one tab, run Quickwit on the following branch `guilload/impl-span-duration-filter` with this command:
```sh
QW_ENABLE_JAEGER_SERVICE=true \
QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER=true \
QW_ENABLE_OPENTELEMETRY_OTLP_SERVICE=true \
OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:7281 \
RUST_BACKTRACE=1 \
RUST_LOG=info,quickwit=info,quickwit_jaeger=debug \
cargo run --manifest-path quickwit/Cargo.toml --all-features -- run
```

In a second tab, run Jaeger:
```sh
docker run --rm --name jaeger-qw \
    -e SPAN_STORAGE_TYPE=grpc-plugin \
    -e GRPC_STORAGE_SERVER=host.docker.internal:7281 \
    -p 5776:5775/udp \
    -p 5779:5778 \
    -p 6833:6831/udp \
    -p 6834:6832/udp \
    -p 7281:7281 \
    -p 14251:14250 \
    -p 14269:14268 \
    -p 16687:16686 \
    jaegertracing/all-in-one:latest
```

Wait for the first split to be published after 30s and then visit `http://localhost:16687/` and click on "Find Traces".

The faulty code in Quickwit lives in the `JaegerService::find_trace_ids` method (`quickwit-jaeger` crate).
